"""Run user test snippets in a subprocess with optional adapter preamble."""

from __future__ import annotations

import json
import subprocess
import sys
import tempfile
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from agentorskill_cli.adapter_schema import AdapterSpec


@dataclass
class SubprocessResult:
    ok: bool
    returncode: int
    stdout: str
    stderr: str
    duration_s: float
    parsed: dict[str, Any] | None = None
    error: str | None = None


def _wrap_body_as_json_main(body: str) -> str:
    """Wrap test body: must define _test() -> dict with keys like ok, metrics."""
    return f"""
def _test():
{body}

if __name__ == "__main__":
    import json, traceback
    try:
        r = _test()
        if not isinstance(r, dict):
            r = {{"ok": False, "error": "not a dict"}}
        print(json.dumps(r, default=str))
    except Exception as e:
        import traceback as tb
        print(json.dumps({{
            "ok": False,
            "error": str(e),
            "trace": tb.format_exc(),
        }}))
"""


def _default_device_block(device: str) -> str:
    """Inject after preamble so torch.randn etc. follow AdapterSpec device (PyTorch 2.1+)."""
    return f"""
import torch
try:
    torch.set_default_device({device!r})
except Exception:
    pass
"""


def build_script(
    adapter: AdapterSpec,
    body: str,
    *,
    include_preamble: bool = True,
    honor_device: bool = False,
) -> str:
    preamble = adapter.enable.preamble if include_preamble else ""
    device_extra = ""
    if honor_device and include_preamble:
        dev = (adapter.device.target_device or "cpu").strip()
        if dev:
            device_extra = _default_device_block(dev)
    return f"""# Generated by agentorskill-cli
{preamble}
{device_extra}

import json
import sys
import time
import traceback

{_wrap_body_as_json_main(body)}
"""


@dataclass
class TestCase:
    id: str
    name: str
    body: str
    include_adapter: bool = True
    timeout: float = 120.0
    category: str = "misc"
    weight: float = 1.0
    counts_toward_adaptation: bool = True


@dataclass
class EvalCaseResult:
    case_id: str
    name: str
    ok: bool
    duration_s: float
    error: str | None
    details: dict[str, Any] = field(default_factory=dict)
    stdout: str = ""
    stderr: str = ""
    category: str = "misc"
    weight: float = 1.0
    counts_toward_adaptation: bool = True
    skipped: bool = False


def run_script(
    source: str,
    *,
    timeout: float = 300.0,
    cwd: Path | None = None,
) -> SubprocessResult:
    with tempfile.NamedTemporaryFile(
        mode="w",
        suffix="_harness.py",
        delete=False,
        encoding="utf-8",
    ) as f:
        f.write(source)
        path = f.name
    t0 = time.perf_counter()
    try:
        proc = subprocess.run(
            [sys.executable, path],
            capture_output=True,
            text=True,
            timeout=timeout,
            cwd=cwd,
            encoding="utf-8",
            errors="replace",
        )
        dt = time.perf_counter() - t0
        out = proc.stdout or ""
        err = proc.stderr or ""
        parsed = None
        if proc.returncode == 0 and out.strip():
            try:
                for line in reversed(out.strip().splitlines()):
                    line = line.strip()
                    if line.startswith("{"):
                        parsed = json.loads(line)
                        break
            except json.JSONDecodeError:
                parsed = None
        err_msg = None
        if not parsed and proc.returncode != 0:
            err_msg = (err or out)[:4000]
        elif parsed and not parsed.get("ok", True):
            err_msg = str(parsed.get("error", "failed"))
        return SubprocessResult(
            ok=proc.returncode == 0 and (parsed is None or parsed.get("ok", True)),
            returncode=proc.returncode,
            stdout=out,
            stderr=err,
            duration_s=dt,
            parsed=parsed,
            error=err_msg,
        )
    except subprocess.TimeoutExpired:
        return SubprocessResult(
            ok=False,
            returncode=-1,
            stdout="",
            stderr="timeout",
            duration_s=time.perf_counter() - t0,
            parsed=None,
            error="timeout",
        )
    finally:
        try:
            Path(path).unlink(missing_ok=True)
        except OSError:
            pass


def run_case(
    adapter: AdapterSpec,
    case: TestCase,
    *,
    honor_device: bool = False,
) -> EvalCaseResult:
    src = build_script(
        adapter,
        case.body,
        include_preamble=case.include_adapter,
        honor_device=honor_device,
    )
    r = run_script(src, timeout=case.timeout)
    details: dict[str, Any] = {}
    if r.parsed:
        details = {k: v for k, v in r.parsed.items() if k not in ("ok", "error", "trace")}
        if "trace" in r.parsed:
            details["trace"] = r.parsed["trace"][:2000]
    skipped = bool(r.parsed and r.parsed.get("skipped"))
    ok = r.ok and (r.parsed is None or r.parsed.get("ok", True))
    if skipped:
        ok = True
    err = r.error
    if r.parsed and not r.parsed.get("ok", True) and not skipped:
        err = str(r.parsed.get("error", err))
    return EvalCaseResult(
        case_id=case.id,
        name=case.name,
        ok=ok,
        duration_s=r.duration_s,
        error=err,
        details=details,
        stdout=r.stdout[:2000],
        stderr=r.stderr[:2000],
        category=case.category,
        weight=case.weight,
        counts_toward_adaptation=case.counts_toward_adaptation,
        skipped=skipped,
    )
